steps:
  - task: PythonScript@0
    displayName: Get project version from .csproj
    inputs:
      scriptSource: inline
      script: |
        import devops_toolset.configure as configure
        import devops_toolset.project_types.dotnet.utils as utils
        configure.main("azuredevops", "en")
        utils.get_csproj_project_version("$(System.DefaultWorkingDirectory)/dotnet-toolset/DotnetToolset.csproj")
  - task: CmdLine@2
    displayName: Build and publish NuGet package
    inputs:
      script: |
        dotnet build -c Release -o $(System.DefaultWorkingDirectory)/.dist
        sudo apt-get install tree
        tree $(System.DefaultWorkingDirectory)
        dotnet nuget push $(System.DefaultWorkingDirectory)/.dist/DotnetToolset.$(PROJECT_VERSION).nupkg --api-key $(NUGET_TOKEN) --source https://api.nuget.org/v3/index.json
